language: ruby
services:
  - docker

stages:
  - name: Test

jobs:
  - stage: Test
    arch: amd64
    os: linux
    script:
      - make TAG=`echo $TRAVIS_COMMIT | cut -c -7`

after_success:
  - bash <(curl -s https://codecov.io/bash)
